version: "3.9"

services:
  portofolio-app:
    build: .
    container_name: portofolio-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true